# Generated by Django 4.2.9 on 2024-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='static/myapp/image/download.png', upload_to='myimage'),
        ),
    ]
